Enforce OAuth2 Issuer and Audience in JWT tokens #1333
reaktivity/nukleus-oauth.java pull request #24
Opened 2019-07-01 18:33 UTC by dknoma

Added auto realm discovery functionality. Allows for ra to enable this. This restores and enhances old functionality that was required before.

2019-07-01 20:30 UTC, dknoma commented
Had to update `ControlIT` as the `oauth` config name was not up-to-date with the naming conventions of other configurations. Added a few tests to make sure that if these names go out of sync, the test will fail meaning the names aren't matching.

2019-07-03 04:40 UTC, jfallows requested changes

2019-07-03 04:40 UTC, jfallows commented on src/test/java/org/reaktivity/nukleus/oauth/internal/control/ControlIT.java
> +
Move these test methods to `OAuthConfigurationTest` in same package as `OAuthConfiguration`, but in the test sources of course.

2019-07-03 04:40 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/oauth/internal/OAuthRealms.java
> +        }
Add a method called `supplyRealm` as follows:
```
OAuthRealm supplyRealm(
    String realmName)
{
    return realmsByName.computeIfAbsent(realmName, OAuthRealm::new);
}
```
...then use it in `OAuthRealms` constructor.
```
if (autoDiscoverRealms)
{
    keysById.keySet().forEach(this::supplyRealm);
}
```

2019-07-03 04:40 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/oauth/internal/OAuthRealms.java
> -
Unintentional whitespace diff?

2019-07-03 04:40 UTC, jfallows commented on pom.xml
> +    <nukleus.oauth.spec.version>develop-SNAPSHOT</nukleus.oauth.spec.version>
Are there any corresponding `nukleus-oauth.spec` changes?
If so, please include a link to the PR.

2019-07-03 18:35 UTC, jfallows approved these changes

2019-07-03 18:35 UTC, merged